=== Alba98/Equipo-6/FASE III (10-05-2022)/RESULTADOS_JORNADAS/resultados_jornadas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="resultados_jornadas" type="resultados_jornadasType" />
   


    <xs:complexType name="resultados_jornadasType">
    <xs:sequence>
      <xs:element name="jornada"  type="jornadaType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="jornadaType">
    <xs:sequence>
      <xs:element name="num_jornada" type="t_num_jornada" />
      <xs:element name="fecha_jornada" type="xs:date"/>
      <xs:element name="partido" type="partidoType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="t_num_jornada">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />  
    </xs:restriction>  
  </xs:simpleType>

    <xs:complexType name="partidoType">
    <xs:sequence>
      <xs:element name="fecha_partido" type="xs:date"/>
    <xs:element name="cod_partido">
        <xs:complexType>
            <xs:attribute name="id_partido" type="cod_partidoType"/>
        </xs:complexType>
    </xs:element>
      <xs:element name="resultado" type="resultadoType"/>
      <xs:element name="nombre_equipo" type="xs:string" maxOccurs="2"/>
    </xs:sequence>
  </xs:complexType>

<xs:simpleType name="cod_partidoType">
  <xs:restriction base="xs:int">
    <xs:minInclusive value="1" />
  </xs:restriction>
</xs:simpleType>
  
<xs:complexType name="resultadoType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="puntuacion" type="t_puntuacion" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>  
  
<xs:simpleType name="t_puntuacion">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-3]-[0-3]"/>    
    </xs:restriction>
</xs:simpleType>  
  
</xs:schema>

=== Alba98/Equipo-6/Consultoria/resources/resultados_jornadas.xml
<?xml version="1.0" encoding="UTF-8"?>
<resultados_jornadas 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="resultados_jornadas.xsd">
    <fecha_expiracion>2022-06-05</fecha_expiracion>
    <jornada num_jornada="1" fecha_jornada="2022-05-08">
         <partido cod_partido="01" hora_partido="17:00:00">
             <resultado>3-0</resultado>
             <nombre_equipo >FNATIC</nombre_equipo>
             <nombre_equipo >G2</nombre_equipo>
         </partido>
         <partido cod_partido="02" hora_partido="19:00:00">
             <resultado>3-0</resultado>
             <nombre_equipo >ASTRALIS</nombre_equipo>
             <nombre_equipo >MISFITS</nombre_equipo>
         </partido>
         <partido cod_partido="03" hora_partido="21:00:00">
             <resultado>0-3</resultado>
             <nombre_equipo >MAD LIONS</nombre_equipo>
             <nombre_equipo >BDS</nombre_equipo>
         </partido>
    </jornada>
    <jornada num_jornada="2" fecha_jornada="2022-05-15">
         <partido cod_partido="04" hora_partido="17:00:00">
             <resultado>3-0</resultado>
             <nombre_equipo >KOI</nombre_equipo>
             <nombre_equipo >GenG</nombre_equipo>
         </partido>
         <partido  cod_partido="05" hora_partido="19:00:00">
             <resultado>3-0</resultado>
             <nombre_equipo >GIANTS</nombre_equipo>
             <nombre_equipo >KC</nombre_equipo>
         </partido>
         <partido  cod_partido="06" hora_partido="21:00:00">
             <resultado>0-3</resultado>
             <nombre_equipo >T1</nombre_equipo>
             <nombre_equipo >TSM</nombre_equipo>
         </partido>
    </jornada>
</resultados_jornadas>

=== Alba98/Equipo-6/FASE III (10-05-2022)/RESULTADOS_JORNADAS/resultados_jornadas_test_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<resultados_jornadas 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="resultados_jornadas.xsd">
    <jornada>
        <num_jornada>1</num_jornada>
         <fecha_jornada>2022-05-08</fecha_jornada> 
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="001" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >FNATIC</nombre_equipo>
             <nombre_equipo >G2</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="002" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >ASTRALIS</nombre_equipo>
             <nombre_equipo >MISFITS</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="003" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >MAD LIONS</nombre_equipo>
             <nombre_equipo >BDS</nombre_equipo>
         </partido>
    </jornada>
    <jornada>
        <num_jornada>2</num_jornada>
         <fecha_jornada>2022-05-15</fecha_jornada> 
         <partido>
             <fecha_partido>2022-05-15</fecha_partido>
             <cod_partido id_partido="004" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >KOI</nombre_equipo>
             <nombre_equipo >GenG</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-15</fecha_partido>
             <cod_partido id_partido="005" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >GIANTS</nombre_equipo>
             <nombre_equipo >KC</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-15</fecha_partido>
             <cod_partido id_partido="006" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >T1</nombre_equipo>
             <nombre_equipo >TSM</nombre_equipo>
         </partido>
    </jornada>
</resultados_jornadas>
