=== Alba98/Equipo-6/FASE III (10-05-2022)/CLASIFICACION/clasificacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="clasificacion" type="clasificacionType"/>
  
  <xs:complexType name="clasificacionType">
    <xs:sequence>
    <xs:element name="fecha_caducidad" type="xs:date" />
    <xs:element name="temporada" type="temporadaType" />
    </xs:sequence>
  </xs:complexType>

<xs:complexType name="temporadaType">
    <xs:sequence>
      <xs:element name="equipo" type="equipoType" minOccurs="2" maxOccurs="unbounded" /> 
    </xs:sequence>
    <xs:attribute name="cod_temporada" type="xs:byte" />
</xs:complexType>

  <xs:complexType name="equipoType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string" />
      <xs:element name="lista_jugadores" type="listajugType" />
    </xs:sequence>
    <xs:attribute name="cod_equipo" type="xs:int" />
    <xs:attribute name="partidos_ganados" type="xs:int" />
  </xs:complexType>
  
  <xs:complexType name="listajugType">
    <xs:sequence>
      <xs:element name="jugador" type="jugadorType" maxOccurs="6" minOccurs="5" />    
    </xs:sequence>  
  </xs:complexType>
  
  <xs:complexType name="jugadorType">
    <xs:sequence>
      <xs:element name="nickname" type="xs:string" />
      <xs:element name="rol" type="xs:string" />
    </xs:sequence>  
  </xs:complexType>
    
  </xs:schema>

=== Alba98/Equipo-6/Consultoria/resources/clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<clasificacion
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="clasificacion.xsd">
    <fecha_expiracion>2022-06-05</fecha_expiracion>
   <temporada cod_temporada="1">
      <equipo cod_equipo="1" partidos_ganados="5">
      <nombre>G2</nombre>
      <lista_jugadores>
          <jugador>
            <nickname>BrokenBlade</nickname>
            <rol>TOP</rol>
          </jugador>
           <jugador>
            <nickname>Jankos</nickname>
            <rol>JGL</rol>
          </jugador>
           <jugador>
            <nickname>CaPs</nickname>
            <rol>MID</rol>
          </jugador>
           <jugador>
            <nickname>Flakked</nickname>
            <rol>ADC</rol>
          </jugador>
           <jugador>
            <nickname>Targamas</nickname>
            <rol>SUPP</rol>
          </jugador>
      </lista_jugadores>
    </equipo>
    <equipo cod_equipo="2" partidos_ganados="6">
      <nombre>FNATIC</nombre>
      <lista_jugadores>
          <jugador>
            <nickname>Wunder</nickname>
            <rol>TOP</rol>
          </jugador>
           <jugador>
            <nickname>Razork</nickname>
            <rol>JGL</rol>
          </jugador>
           <jugador>
            <nickname>Humanoid</nickname>
            <rol>MID</rol>
          </jugador>
           <jugador>
            <nickname>Upset</nickname>
            <rol>ADC</rol>
          </jugador>
           <jugador>
            <nickname>Hylissang</nickname>
            <rol>SUPP</rol>
          </jugador>
      </lista_jugadores>
    </equipo>
    </temporada>
</clasificacion>
