=== Alba98/Equipo-6/FASE III/ULTIMA_JORNADA/resultados_ultima_J.dtd
<!ELEMENT ultima_jornada (jornada)>
<!ELEMENT jornada ((num_jornada,fecha_jornada,partido*))>
<!ELEMENT num_jornada (#PCDATA)>
<!ELEMENT fecha_jornada (#PCDATA)>
<!ELEMENT partido ((fecha_partido,cod_partido,resultado,nombre_equipo+))>
<!ELEMENT fecha_partido (#PCDATA)>
<!ELEMENT cod_partido (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT nombre_equipo (#PCDATA)>
<!ATTLIST cod_partido id_partido CDATA #REQUIRED>
<!ATTLIST resultado puntuacion NMTOKEN #REQUIRED>

=== Alba98/Equipo-6/FASE III/ULTIMA_JORNADA/resultado_ultima_jornada_test_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ultima_jornada SYSTEM "resultados_ultima_J.dtd">
<ultima_jornada>
    <jornada>
        <num_jornada>1</num_jornada>
         <fecha_jornada>2022-05-08</fecha_jornada> 
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="001" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >FNATIC</nombre_equipo>
             <nombre_equipo >G2</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="002" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >ASTRALIS</nombre_equipo>
             <nombre_equipo >MISFITS</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="003" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >MAD LIONS</nombre_equipo>
             <nombre_equipo >BDS</nombre_equipo>
         </partido>
    </jornada>
</ultima_jornada>
