=== Alba98/Equipo-6/FASE III(09-05-2022)/RESULTADOS_JORNADAS/resultados_J.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resultados_jornadas (jornada*)>
<!ELEMENT jornada ((num_jornada,fecha_jornada,partido)*)>
<!ELEMENT num_jornada (#PCDATA)>
<!ELEMENT fecha_jornada (#PCDATA)>
<!ELEMENT partido ((fecha_partido,cod_partido,resultado,nombre_equipo)*)>
<!ELEMENT fecha_partido (#PCDATA)>
<!ELEMENT cod_partido (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT nombre_equipo (#PCDATA)>

=== Alba98/Equipo-6/FASE III(09-05-2022)/RESULTADOS_JORNADAS/resultados_jornadas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- DEFINICIÃ“N DEL TIPO DE DOCUMENTO -->
<!DOCTYPE resultados_jornadas SYSTEM "resultados_J.dtd"[
]>
<resultados_jornadas>
    <jornada>
        <num_jornada></num_jornada>
         <fecha_jornada></fecha_jornada> 
         <partido>
             <fecha_partido></fecha_partido>
             <cod_partido></cod_partido>
             <resultado></resultado>
             <nombre_equipo ></nombre_equipo>
         </partido>
    </jornada>
</resultados_jornadas>

=== Alba98/Equipo-6/FASE III (10-05-2022)/RESULTADOS_JORNADAS/resultados_jornadas_test_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE resultados_jornadas SYSTEM "resultados_J.dtd">
<resultados_jornadas>
    <jornada>
        <num_jornada>1</num_jornada>
         <fecha_jornada>2022-05-08</fecha_jornada> 
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="001" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >FNATIC</nombre_equipo>
             <nombre_equipo >G2</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="002" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >ASTRALIS</nombre_equipo>
             <nombre_equipo >MISFITS</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="003" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >MAD LIONS</nombre_equipo>
             <nombre_equipo >BDS</nombre_equipo>
         </partido>
    </jornada>
    <jornada>
        <num_jornada>2</num_jornada>
         <fecha_jornada>2022-05-15</fecha_jornada> 
         <partido>
             <fecha_partido>2022-05-15</fecha_partido>
             <cod_partido id_partido="004" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >KOI</nombre_equipo>
             <nombre_equipo >GenG</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-15</fecha_partido>
             <cod_partido id_partido="005" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >GIANTS</nombre_equipo>
             <nombre_equipo >KC</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-15</fecha_partido>
             <cod_partido id_partido="006" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >T1</nombre_equipo>
             <nombre_equipo >TSM</nombre_equipo>
         </partido>
    </jornada>
</resultados_jornadas>
