=== Alba98/Equipo-6/FASE III (10-05-2022)/ULTIMA_JORNADA/resultados_ultima_J.dtd
<!ELEMENT ultima_jornada (fecha_expiracion, jornada)>
<!ELEMENT fecha_expiracion (#PCDATA)>
<!ELEMENT jornada (partido+)>
<!ELEMENT partido ((resultado,nombre_equipo+))>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT nombre_equipo (#PCDATA)>
<!ATTLIST jornada num_jornada CDATA #REQUIRED>
<!ATTLIST jornada fecha_jornada CDATA #REQUIRED>
<!ATTLIST partido cod_partido CDATA #REQUIRED>
<!ATTLIST partido hora_partido CDATA #REQUIRED>

=== Alba98/Equipo-6/Consultoria/resources/resultado_ultima_jornada.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ultima_jornada SYSTEM "resultados_ultima_J.dtd">
<ultima_jornada>
    <fecha_expiracion>2022-05-17</fecha_expiracion>
    <jornada num_jornada="1" fecha_jornada="2022-05-08">
         <partido cod_partido="01" hora_partido="17:00:00">
             <resultado>3-0</resultado>
             <nombre_equipo >FNATIC</nombre_equipo>
             <nombre_equipo >G2</nombre_equipo>
         </partido>
         <partido cod_partido="02" hora_partido="19:00:00">
             <resultado>0-3</resultado>
             <nombre_equipo >ASTRALIS</nombre_equipo>
             <nombre_equipo >MISFITS</nombre_equipo>
         </partido>
         <partido cod_partido="03" hora_partido="21:00:00">
             <resultado>3-0</resultado>
             <nombre_equipo >MAD LIONS</nombre_equipo>
             <nombre_equipo >BDS</nombre_equipo>
         </partido>
    </jornada>
</ultima_jornada>
