=== Alba98/Equipo-6/FASE III (10-05-2022)/ULTIMA_JORNADA/ultima_jornada.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ultima_jornada" type="ultima_jornadaType" />
   
  <xs:complexType name="ultima_jornadaType">
    <xs:sequence>
      <xs:element name="fecha_expiracion" type="xs:date" />
      <xs:element name="jornada"  type="jornadaType" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="jornadaType">
    <xs:sequence>
      <xs:element name="partido" type="partidoType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="num_jornada" type="t_num_jornada" />
    <xs:attribute name="fecha_jornada" type="xs:date"/>
  </xs:complexType>
  
  <xs:simpleType name="t_num_jornada">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>  
  </xs:simpleType>

    <xs:complexType name="partidoType">
    <xs:sequence>
      <xs:element name="resultado" type="resultadoType"/>
      <xs:element name="nombre_equipo" type="xs:string" maxOccurs="2"/>
    </xs:sequence>
    <xs:attribute name="cod_partido" type="cod_partidoType" />
    <xs:attribute name="hora_partido" type="xs:time" />
  </xs:complexType>

  <xs:simpleType name="cod_partidoType">
  <xs:restriction base="xs:int">
    <xs:minInclusive value="1" />
  </xs:restriction>
</xs:simpleType>
  
<xs:simpleType name="resultadoType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-3]-[0-3]"/>    
    </xs:restriction>
</xs:simpleType>
  
</xs:schema>

=== Alba98/Equipo-6/FASE III (10-05-2022)/ULTIMA_JORNADA/ultima_jornada_test_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<ultima_jornada 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ultima_jornada.xsd">
    <fecha_expiracion>2022-05-17</fecha_expiracion>
    <jornada num_jornada="1" fecha_jornada="2022-05-08">
         <partido cod_partido="01" hora_partido="17:00:00">
             <resultado>3-0</resultado>
             <nombre_equipo>FNATIC</nombre_equipo>
             <nombre_equipo >G2</nombre_equipo>
         </partido>
         <partido cod_partido="02" hora_partido="19:00:00">
             <resultado>0-3</resultado>
             <nombre_equipo >ASTRALIS</nombre_equipo>
             <nombre_equipo >MISFITS</nombre_equipo>
         </partido>
         <partido cod_partido="03" hora_partido="21:00:00">
             <resultado>3-0</resultado>
             <nombre_equipo >MAD LIONS</nombre_equipo>
             <nombre_equipo >BDS</nombre_equipo>
         </partido>
    </jornada>
</ultima_jornada>

=== Alba98/Equipo-6/FASE III/ULTIMA_JORNADA/ultima_jornada_test_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<ultima_jornada 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ultima_jornada.xsd">
    <jornada>
        <num_jornada>1</num_jornada>
         <fecha_jornada>2022-05-08</fecha_jornada> 
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="001" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >FNATIC</nombre_equipo>
             <nombre_equipo >G2</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="002" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >ASTRALIS</nombre_equipo>
             <nombre_equipo >MISFITS</nombre_equipo>
         </partido>
         <partido>
             <fecha_partido>2022-05-08</fecha_partido>
             <cod_partido id_partido="003" />
             <resultado puntuacion="3-0" />
             <nombre_equipo >MAD LIONS</nombre_equipo>
             <nombre_equipo >BDS</nombre_equipo>
         </partido>
    </jornada>
</ultima_jornada>
